mysite/mysite/urls.py
"""from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]"""

from django.urls import include, path
from django.contrib import admin
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/polls/models.py
# Create your models here.
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

def __str__(self):
    return self.question_text

def was_published_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.pub_date <= now

was_published_recently.admin_order_field = 'pub_date'
was_published_recently.boolean = True
was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

mysite/mysite/views.py
from django.shortcuts import render
def home(request):
    return render(request, 'index.html')

mysite/polls/views.py
# Create your views here.
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Choice, Question
from django.utils import timezone
from django.template.response import TemplateResponse
from django.views import View
from django.http import HttpResponse
from django.template.loader import get_template

class IndexView(View):
    latest_question_list = Question.objects.filter(
        pub_date__lte=timezone.now()
    ).order_by('-pub_date')[:5]

    def get(self, request):
        template = get_template('polls/index.html')
        context = {'latest_question_list': self.latest_question_list}
        output = template.render(context, request)
        return HttpResponse(output)

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return TemplateResponse(request, 'polls/results.html', {'question': question})
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        context = {
            'question': question,
            'error_message': "You didn't select a choice.",
        }
        return TemplateResponse(request, 'polls/detail.html', context)
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/detail.html
{% load blocks_tags %}

{% get_header %}
{% get_sidebar %}

<div id="content">
<h1>{{ question.question_text }}</h1>

{% if error_message %}<h3 class="KeyError">{{ error_message }}</h3>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
</div>

{% get_footer %}

mysite/polls/templates/polls/footer.html
    </body>
</html> 

mysite/polls/templates/polls/header.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
<title>Polls Application</title>
<link rel="stylesheet" type="text/css" href="{% static 'mysite/style.css' %}" />
</head>

<body>
<h2> Sample Python: Django Project </h2>

mysite/polls/templates/polls/index.html
{% load blocks_tags %}

{% get_header %}
{% get_sidebar %}

<div id="content">
<h1>Welcome!</h1>
<p>
This is a sample project on Django using the Python programming language.
We learn a lot: Modeling and database manipulation, designing the view and
URL mapping, template and custom template tags, using secure form,
customizing the admin site, using static files, and more.
</p>
</div>

{% get_footer %}

mysite/polls/templates/polls/results.html
{% load blocks_tags %}

{% get_header %}
{% get_sidebar %}

<div id="content">
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</div>

{% get_footer %}

mysite/polls/templates/polls/sidebar.html
<div id="sidebar">
    <p><a href= "{% url 'home' %}">Home</a></p>
    <p><a href= "/docs/">Documentation</a></p>
    <p><a href= "{% url 'polls:index' %}">Polls</a></p>
    <p><a href= "/admin/">Admin</a></p>
</div>

mysite/templates/index.html
{% load blocks_tags %}

{% get_header %}
{% get_sidebar %}

<div id="content">
<h1>Welcome!</h1>
<p>
This is a sample project on Django using the Python programming language.
We learn a lot: Modeling and database manipulation, designing the view and
URL mapping, template and custom template tags, using secure form,
customizing the admin site, using static files, and more.
</p>
</div>

{% get_footer %}